<script>
$(document).ready(function(){
	$('#email').focus();
	$('#loginForm').validate({
		submitHandler: function(form) {
			$.fancybox.showActivity();
			$(form).ajaxSubmit({
				success: function(data) {
					$.fancybox.hideActivity();
					if (data == '1') {
						try { 
							parent.$.fancybox.close();
							parent.window.location = parent.window.location.href;
						} catch (e) {
							window.location = '';
						}
					} else {
						alert('username or password incorrect.');
					}
				}
			});
	   	}
	});
});
</script>
<form id="loginForm" method="post" action="/login">
email:
<br />
<input id="email" name="email" type="text" class="required email" />
<br />
<br />
password:
<br />
<input name="password" type="password" class="required" />
<br />
<br />
<input type="submit" value="login" />
</form>