<script>
$(document).ready(function(){
	$('#<?php echo $this->filter; ?>_subtabs').tabs();
});
</script>
<div id="<?php echo $this->filter; ?>_subtabs">
  <ul>
    <?php if ($this->filter == 'calendar') : ?>
     <li><a href="/updates/calendar-view?range=today"><span>Today</span></a></li>
    <li><a href="/updates/calendar-view?range=week"><span>This Week</span></a></li>
    <?php else : ?>
    <li><a href="/updates/view?type=project&filter=<?php echo $this->filter; ?>"><span>Projects</span></a></li>
    <li><a href="/updates/view?type=user&filter=<?php echo $this->filter; ?>"><span>Users</span></a></li>
    <?php endif; ?>
  </ul>
</div>