<html>
<head>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/jquery/cupertino/jquery-ui-1.8.1.custom.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/jquery/jquery.contextMenu.css" />
<script src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.4.2.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-ui-1.8.1.custom.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery.cycle.all.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery.qtip-1.0.0-rc3.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery.contextMenu.js"></script>
</head>
<body style="background-image:url(<?php echo $this->baseUrl(); ?>/images/new_bg2.jpg);background-attachment:fixed;background-repeat:no-repeat;background-color:rgb(14, 71, 138);" />
  <div style="display:table;">
    <div style="display:table-cell;padding:10px;">
      advertisements
      <div style="margin:10px;background-color:#f99;width:200px;">
      <?php 
      echo 'role: ' . Wevolt_Acl::getInstance()->getUserRole() . '<br />';
      if (Zend_Auth::getInstance()->hasIdentity()) {
	      echo 'welcome, ' . Zend_Auth::getInstance()->getIdentity()->username . 
	      '<br />' . 
	      '<button onclick="window.location=\'/logout\';">logout</button>';
      } else {
      	  echo '<button onclick="window.location=\'/login\';">login</button>';
      }
      ?>
      </div>
    </div>
    <div style="display:table-cell;width:100%;padding:10px;">
      <div style="margin-bottom:10px;">
        big header
      </div>
      <?php echo $this->layout()->content; ?>
    </div>
  </div>
</body>
</html>