<html>
<head>
<link rel="stylesheet" href="/css/global.css?cache=<?php echo date('Y-m-d H:i:s'); ?>" />

<script src="/js/jquery/jquery-1.4.2.js"></script>

<script src="/js/jquery/ui/main-1.8.1.custom.min.js"></script>
<link rel="stylesheet" href="/js/jquery/ui/cupertino/jquery-ui-1.8.1.custom.css" />

<script src="/js/jquery/fancybox/main-1.3.1.js"></script>
<link rel="stylesheet" href="/js/jquery/fancybox/jquery.fancybox-1.3.1.css" />

<!--<script src="/js/jquery/jqgrid/locale-en.js"></script>-->
<!--<script src="/js/jquery/jqgrid/main.js"></script>-->
<!--<link rel="stylesheet" href="/js/jquery/jqgrid/main.css" />-->

<script src="/js/jquery/contextmenu/jquery.contextMenu.js"></script>
<link rel="stylesheet" href="/js/jquery/contextmenu/jquery.contextMenu.css" />

<script src="/js/jquery/fullcalendar/fullcalendar.js"></script>
<link rel="stylesheet" href="/js/jquery/fullcalendar/fullcalendar.css" />

<script src="/js/jquery/form/main.js"></script>
<script src="/js/jquery/from/validate.js"></script>
<script src="/js/jquery/cycle/jquery.cycle.all.js"></script>
<script src="/js/jquery/qtip/jquery.qtip-1.0.0-rc3.js"></script>
<script src="/js/jquery/easing-1.3.js"></script>

<!--<script src="/js/ext/ext-jquery-adapter.js"></script>-->
<!--<script src="/js/ext/ext-all.js"></script>-->
<!--<link rel="stylesheet" href="/js/ext/xtheme-blue.css" />-->

</head>
<body>
  <div class="table space">
    <div class="row">
      <div class="cell top">
        <div class="pad-bottom">
          <a href="/"><img src="/images/wevolt_logo_no_tag.png" /></a>
        </div>
        <?php if (!Zend_Auth::getInstance()->hasIdentity()) : ?>
          <div class="pad-bottom">
            <?php echo $this->partial('_getstarted.php'); ?>
          </div>
        <?php endif; ?>
        <div class="pad-bottom">
            <?php echo $this->partial('_spotlight.php'); ?>
        </div>
        <span>
          <a href="http://www.wowio.com/">2010 WOWIO</a> | 
          <a href="/faqs/privacy">Privacy Policy</a> | 
          <a href="/faqs/terms">Terms of Use</a>
        </span>
      </div>
      <div class="cell top no-space">
        <div style="height:90px;">big header</div>
        <?php echo $this->layout()->content; ?>
      </div>
    </div>
  </div>
  <?php echo $this->partial('_toolbar.php'); ?>
</body>
</html>