<html>
<head>
<link rel="stylesheet" href="/css/global.css?cache=<?php echo date('Y-m-d H:i:s'); ?>" />
<link rel="stylesheet" href="/css/jquery/cupertino/jquery-ui-1.8.1.custom.css" />
<link rel="stylesheet" href="/css/jquery/jquery.contextMenu.css" />
<link rel="stylesheet" href="/css/jquery/fancybox/jquery.fancybox-1.3.1.css" />
<script src="/js/jquery/jquery-1.4.2.min.js"></script>
<script src="/js/jquery/jquery-ui-1.8.1.custom.min.js"></script>
<script src="/js/jquery/fancybox/jquery.fancybox-1.3.1.js"></script>
<script src="/js/jquery/jquery.form.js"></script>
<script src="/js/jquery/jquery.validate.js"></script>
<script src="/js/jquery/jquery.cycle.all.js"></script>
<script src="/js/jquery/jquery.qtip-1.0.0-rc3.js"></script>
<script src="/js/jquery/jquery.contextMenu.js"></script>
<script src="/js/jquery/fancybox/jquery.easing-1.3.pack.js"></script>
<!--<script src="/js/jquery/fancybox/jquery.mousewheel-3.0.2.pack.js"></script>-->
<script src="/js/jquery/fullcalendar.js"></script>
</head>
<body>
  <div class="table">
    <div class="cell center pad" style="width:300px;">
      <a href="/"><img src="/images/wevolt_logo_no_tag.png" /></a>
      <?php if (Wevolt_Acl::getInstance()->getUserRole() == 'guest') : ?>
        <?php echo $this->partial('_getstarted.php'); ?>
      <?php endif; ?>
      <?php echo $this->partial('_spotlight.php'); ?>
      <div class="center">
        <a href="http://www.wowio.com/">2010 WOWIO</a> | 
        <a href="/faqs/privacy">Privacy Policy</a> | 
        <a href="/faqs/terms">Terms of Use</a>
      </div>
    </div>
    <div class="cell pad">
      <div class="push">
        big header
      </div>
      <?php echo $this->layout()->content; ?>
    </div>
  </div>
  <?php echo $this->partial('_toolbar.php'); ?>
</body>
</html>