PRIVACY POLICY<br>



<strong>Personal Information We May Collect</strong>



<p>This Website may collect personally-identifiable information and non-personally identifiable information about you.</p><br>



Personally-identifiable information you provide to us may include the following: your name and home address, your home phone number, your email address, your financial information, such as credit card numbers, your household income, your education and work experience, and other details of your personal life, such as your hobbies.<p><br>



Non-personally identifiable information may include the type of browser you are using, your IP address, and your Internet service provider.</p><p><br>



This Website may also use cookies, which typically allow you to navigate between different web pages without losing the information you supplied at the start of any session. You may be able to accept or decline cookies depending on the capabilities and configuration of your browser. Most browsers automatically accept cookies and can be configured to decline cookies if you so desire. However, if you decline cookies, it may affect your ability to experience certain features of this Website. W3VOLT cannot and does not assume responsibility for any technical limitations or malfunction of your browser or for use of cookies by third parties that provide hosting or other services for this Website.</p><p><br>



This Website typically uses such non-personally identifiable information to accumulate aggregate data on the Website, for tracking purposes or to provide you with additional products or services.<br>

<br>

<strong>Use of Personal Information</strong>


</p><p>This Website may use your personal information to complete transactions you request or to send you communications about your account, your submissions, or about new features on this Website. We may also use your personal information to send you promotional materials, including special offers and promotions.<br>
<br>

</p><p><strong>Access to Personal Information</strong><br>


</p><p>We may share your personal information with our affiliates or other companies in our corporate family. We may provide your personal information to other companies whom we may utilize in processing our online transactions or other services. We may be required by law to disclose your personal information, such as in response to a court order or subpoena or at a law enforcement agency's request, and we reserve the right to do so. We may share your personal information as part of a purchase or sale pursuant to appropriate confidentiality provisions, such as if W3VOLT merges with another company or sells a business division.<br>
<br>

</p><p><strong>Opt-Out Choices</strong><br>


</p><p>You may always choose to opt out of receiving promotional materials. If you wish to opt out of receiving such correspondence, please follow the opt-out instructions included in the applicable correspondence.
Updating or Correcting Your Personal Information<br>
<br>


</p><p>If you wish to review, update or correct any of your personal information in this Website's possession, please contact us using the contact information provided below.<br>
<br>

<strong>Security Measures</strong>

</p><p>Not all information provided while using this Website is necessarily secure against electronic interception or tampering. While this Website does incorporate secure software and encryption to protect certain sensitive information you may provide, as with any Internet transmission, there is always some element of risk in sending personal information. For that reason, W3VOLT cannot guarantee that all personal or other sensitive information will remain confidential, and we must disclaim any liability for the inadvertent or unknowing disclosure or use of such information.<br>
<br>

</p><p><strong>Child Online Privacy</strong>

</p><p>This Website is not generally intended for anyone under the age of 18. We do not knowingly collect personal information from children under the age of 13. If you are 13 or under, please do not submit your personal information on this Website.<br>
<br>

</p><p><strong>Links to Other Sites</strong><br>


</p><p>This Website may contain links to other sites. We are not responsible for the privacy policies or practices, content, or any other aspect of these other sites, and you link to them at your own risk.<br>

</p><p><strong>Changes to this Privacy Policy</strong>


</p><p>We may change this Website's policies concerning the use of your personal information and other privacy policies from time to time. We will post any such changes on this Website. For that reason, we encourage you to periodically review this privacy policy to keep yourself informed of any changes.<br>
<br>

<strong>How to Contact Us</strong>


</p><p>We encourage you to share any comments or concerns you may have about this privacy policy or other aspects of this Website at the address given below. However, please note that by accessing this Website or submitting your personal information, you acknowledge and agree to be bound by this privacy statement, as amended or revised from time to time, in addition to all other terms of use posted at this Website.<br>
<br>

</p><p>For questions about this privacy policy or to contact us:<br>


</p><p>WOWIO Inc<br>

Los Angeles, CA 90064<br>


info@wevolt.com
	</p>