<script>
$(document).ready(function(){
	$("#changePassForm").validate({
		submitHandler: function(form) {
			$(form).ajaxSubmit();
		}
	})
});
</script>
<form id="changePassForm" action="/user/settings/change-password" method="post">
  <input type="hidden" name="ajax" value="1" />
  old password:
  <br />
  <input type="password" name="old_password" />
  <br />
  <br />
  new password:
  <br />
  <input type="password" name="new_password" />
  <br />
  <br />
  confirm new password:
  <br />
  <input type="password" name="confirm_password" />
</form>