<link rel="stylesheet" href="/css/jquery/fullcalendar.css" />
<script src="/js/jquery/fullcalendar.js"></script>
<script>
$(document).ready(function() {
	var eventArray = new Array();
	$('#calendar').fullCalendar({
		theme: true,
		header: {
			left:   'prev,next today<?php echo ($this->owner) ? ' add edit trash' : ''; ?>',
	    	center: 'title',
	    	right:  'sort month,basicWeek,basicDay'
		},
		allDayDefault: false,
		defaultView: '<?php echo $this->view; ?>',
		year: '<?php echo $this->year; ?>',
		month: '<?php echo $this->month; ?>',
		date: '<?php echo $this->day; ?>',
		userid: '<?php echo $this->id; ?>',
		events: '/calendar/get-events',
		eventRender: function(event, element, view) {
			var html = '<a  href="javascript:void(0)" onclick="view_event(\'view\',\''+event.id+'\');">';
			element.attr('eventid', event.id);
			element.attr('encryptid', event.encrypt_id);
			element.addClass(event.type);
			if (view.name == 'month') {
				if ( event.thumb != '') {
					html += '<img src="' + event.thumb + '" width="25" height="25" />';
				} else {
					html += '<div style="font-size:10px;"><b><i>' + event.title + '</i></b></div>';
				}
			} else if (view.name == 'basicWeek') {
				if ( event.thumb != '') {
					html += '<div><img src="' + event.thumb + '" width="50" height="50" /></div>';
				}
			    html += '<div><span style="font-size:10px;">' + $.fullCalendar.formatDate(event.start, 'h:mm tt');
				if (event.end) {
					html += ' - ' + $.fullCalendar.formatDate(event.end, 'h:mm tt');
				}
				html += '</span></div><div style="font-size:10px;">';
				html += '<b><i>' + event.title + '</i></b>';
				html += '</div>';
			}else if (view.name == 'basicDay') {
				html += '<table cellspacing="0" cellpadding="0"><tr>';
				if ( event.thumb != '') {
					html += '<td width="50" valign="top"><div><img src="' + event.thumb + '" width="40" height="40" hspace="5"/></div></td>';
				}
				html += '<td width="150" valign="top" style="background-color:#e5e5e5; border:1px #666666 solid; padding:2px;overflow:hidden;height:40px;"><div style="overflow:hidden;height:40px;">';
				html += '<div style="font-size:10px;"><b><i>' + event.title + '</i></b></div></div></td></tr></table>';
			}
			html += '</a>';
			element.html(html);
	    },
		eventAfterRender: function(event, element, view) {
	    	<?php if ($this->owner) : ?>
			element.draggable({
				revert: true,
				helper: 'clone',
				appendTo: 'body',
				opacity: .5
			});
			<?php endif; ?>
			switch (view.name) {
				case 'month':
					var content = '<div>' + $.fullCalendar.formatDate(event.start, 'h:mm tt') + ' - ' + event.type + '</div><hr /><div><b><i>' + event.title + '</i></b></div><div>' + event.description + '</div>';
					break;
				default:
					var content = '<div>' + event.type + '</div><hr /><div>' + event.description + '</div>';
			}
			element.qtip({
				content: content,
				position: {
					target: 'mouse',
					adjust: {
						screen: true
					}
				},
				style: {
					name: 'blue'
				}
			});
	    }
	});
	$('#calendar_selector').change(function(value){
		$('#calendar').fullCalendar('type', $(this).val()); 
		$('#calendar').fullCalendar('refetchEvents');
	});
<?php if ($this->owner) : ?>
	$('#cal_add_button').click(function(){
		window.location='/calendar/add';
//		$.fancybox({
//			href:'/calendar/add',
//			type:'iframe',
//			width:800,
//			height:600,
//			onClosed: function() {
//				$('#calendar').fullCalendar('refetchEvents');
//			}
//		});
	});
	$('#cal_edit_button').qtip({
		content: 'Drag events here to edit them.',
		position: {
			target: 'mouse',
			adjust: {
				screen: true
			}
		},
		style: {
			name: 'blue'
		}
	});
	$('#cal_edit_button').droppable({
		tolerance: 'pointer',
		over: function() {
			$(this).attr('src', '/images/silk/edit_on.png');
		},
		out: function() {
			$(this).attr('src', '/images/silk/edit_off.png');
		},
		drop: function(event, ui) {
			$(this).attr('src', '/images/silk/edit_off.png');
			// edit page
//			open_event_wizard('edit', ui.draggable.attr('encryptid'));
//			console.log(eventId);
			window.location='/calendar/edit?id=' + $(ui.draggable).attr('eventid');
		}
	});
	$('#cal_trash_button').qtip({
		content: 'Drag events here to delete them.',
		position: {
			target: 'mouse',
			adjust: {
				screen: true
			}
		},
		style: {
			name: 'blue'
		}
	});
	$('#cal_trash_button').droppable({
		tolerance: 'pointer',
		over: function() {
			$(this).attr('src', '/images/silk/trash_on.png');
		},
		out: function() {
			$(this).attr('src', '/images/silk/trash_off.png');
		},
		drop: function(event, ui) {
			var ans = confirm('are you sure you want to delte this event?');
			if (ans) {
				$.post('/calendar/delete', {id: ui.draggable.attr('eventid')}, function() {
					$('#calendar').fullCalendar('refetchEvents');
				});
			}
			$(this).attr('src', '/images/silk/trash_off.png');
		}
	});
<?php endif; ?>
});
</script>
<div class="panel_top">
  <div class="table">
    <div class="cell middle">Calendar</div>
  </div>
</div>
<div id="calendar"></div>