<link rel="stylesheet" href="/css/jquery/fullcalendar.css" />
<script src="/js/jquery/fullcalendar.js"></script>
<script>
$(document).ready(function() {
	$('#calendar').fullCalendar({
		theme: true,
		header: {
			left:   'prev,next today',
	    	center: 'title',
	    	right:  'sort month,basicWeek,basicDay'
		},
		allDayDefault: false,
		defaultView: '<?php echo $this->view; ?>',
		year: '<?php echo $this->year; ?>',
		month: '<?php echo $this->month; ?>',
		date: '<?php echo $this->day; ?>',
		userid: '<?php echo $this->id; ?>',
		events: '/calendar/get-events',
		eventRender: function(event, element, view) {
			if (view.name == 'month') {
				var html ='<a href="http://www.wevolt.com/view_event.php?event='+event.id+'">';
				if ( event.thumb != '') {
					html += '<img style="border:solid 1px #000;" src="' + event.thumb + '" width="25" height="25" />';
				} else {
					html += '<div style="font-size:10px;"><b><i>' + event.title + '</i></b></div>';
					 html += '</a>';
				}
			} else if (view.name == 'basicWeek') {
				var html = '<a href="http://www.wevolt.com/view_event.php?event='+event.id+'">';
				if ( event.thumb != '') {
					html += '<img style="border:solid 1px #000;" src="' + event.thumb + '" width="50" height="50" />';
				}
				html += '<div><span style="font-size:10px;">' + $.fullCalendar.formatDate(event.start, 'h:mm tt');
				if (event.end) {
					html += ' - ' + $.fullCalendar.formatDate(event.end, 'h:mm tt');
				}
				html += '</span></div><div style="font-size:10px;">';
				html += '<b><i>' + event.title + '</i></b>';
				html += '</div></a>';
			} else if (view.name == 'basicDay') {
				var html = '<a href="http://www.wevolt.com/view_event.php?event='+event.id+'"><table cellspacing="0" cellpadding="0"><tr>';
				if ( event.thumb != '') {
					html += '<td width="50" valign="top"><div><a href="http://www.wevolt.com/view_event.php?event='+event.id+'"><img style="border:solid 1px #000;" src="' + event.thumb + '" width="40" height="40" hspace="5"/></a></div></td>';
				}
				html += '<td width="150" valign="top" style="background-color:#e5e5e5; border:1px #666666 solid; padding:2px;overflow:hidden;height:40px;"><div style="overflow:hidden;height:40px;">';
				html += '<div style="font-size:10px;"><b><i>' + event.title + '</i></b></div></div>' + 
						'</td></tr></table></a>';
			}
			html += '<ul style="display:none;" id="eventmenu_' + event.id + '">' + 
	  		  '<li>' + 
	    	    '<a href="#delete">delete</a>' + 
	  		  '</li>' + 
			'</ul>';
			element.html(html);
	    },
		eventAfterRender: function(event, element, view) {
	    	<?php if ($this->owner) : ?>
			element.contextMenu(
				{menu: 'eventmenu_' + event.id},
				function(action, el) {
					if (action == 'delete') {
						$.post('/calendar/delete', 
							   {id: event.id},
							   function() {
								   $('#calendar').fullCalendar('refetchEvents');
							   }
						);
					}
				}
			);	
			<?php endif; ?>
			if (view.name == 'month') {
				element.css('width', '52px');
				element.qtip({
					content: '<div>' + $.fullCalendar.formatDate(event.start, 'h:mm tt') + ' - ' + event.type + '</div><hr /><div><b><i>' + event.title + '</i></b></div><div>' + event.description + '</div>',
					position: {
						target: 'mouse',
						adjust: {
							screen: true
						}
					},
					style: {
						name: 'blue'
					}
				});
			} else if (view.name == 'basicWeek') {
				element.css('height', 'auto');
				element.css('width', '150px');
				element.qtip({
					content: '<div>' + event.type + '</div><hr /><div>' + event.description + '</div>',
					position: {
						target: 'mouse',
						adjust: {
							screen: true
						}
					},
					style: {
						name: 'blue'
					}
				});
			} else if (view.name == 'basicDay') {
				element.css('height', 'auto');
				element.css('width', '150px');
				element.contextMenu({
					menu: 'eventmenu_' + event.id
				});	
				element.qtip({
					content: '<div>' + event.type + '</div><hr /><div>' + event.description + '</div>',
					position: {
						target: 'mouse',
						adjust: {
							screen: true
						}
					},
					style: {
						name: 'blue'
					}
				});
			
			}
	    }
	});
	$('#calendar_selector').change(function(value){
		$('#calendar').fullCalendar('type', $(this).val()); 
		$('#calendar').fullCalendar('refetchEvents');
	});
	$('#addEvent').click(function(){
//		$.fancybox({
//			href:'/calendar/add',
//			type:'iframe',
//			width:800,
//			height:600,
//			onClosed: function() {
//				$('#calendar').fullCalendar('refetchEvents');
//			}
//		});
		window.location='/calendar/add';
	});
//	$('.delete_event').live('click', function(){
//		var ans = confirm('are you sure you want to delte this?');
//		if (ans) {
//			alert('yes');
//		}
//	});
});
</script>
<?php if ($this->owner) : ?>
<script>

</script>
<div>
  <button id="addEvent">add event</button>
</div>
<?php endif; ?>
<div class="panel_top">
  <div class="table">
    <div class="cell middle">Calendar</div>
  </div>
</div>
<div id="calendar"></div>